name: .NET Core

on: [push]

jobs:
  testStuffOut:
    runs-on: windows-latest
    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1
    # use msbuild to build VS solution
    - name: test
      run: |
        ls
    - name: build solution
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\MSBuild.exe TestGit.sln"
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" TestGit.sln
