name: DotNet

on: [push]

jobs:
  BuildRunTestsAndPublishNuget:
    runs-on: windows-latest
    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1
    - name: download nuget
      uses: warrenbuckley/Setup-Nuget@v1
    - name: restore nuget packages
      run: |
        echo "nuget.exe restore TestGit.sln"
        nuget.exe restore TestGit.sln
    - name: build solution
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\MSBuild.exe"
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" TestGit.sln
      shell: cmd 
    - name: check sql
      run: |
        sqlcmd -?
      shell: cmd
    - name: run tests
      run: |
        echo "TestGit\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe TestGit.Tests\bin\Debug\TestGit.Tests.dll"
        "packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" TestGit.Tests\bin\Debug\TestGit.Tests.dll
      shell: cmd
    - name: Generate build number
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.GITHUB_TOKEN}}        
    - name: Print new build number
      run: echo Build number is $BUILD_NUMBER - ${{ steps.buildnumber.outputs.build_number }}
      shell: bash
    - name: Setup Nuget and Push Package
      run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/gblock0/index.json" -UserName gblock0 -Password ${{ secrets.GITHUB_TOKEN }}
        nuget pack TestGit/TestGit.nuspec -Version $BUILD_NUMBER
        nuget setapikey ${{ secrets.GITHUB_TOKEN }} -Source "GitHub"
        ls
        ls TestGit
        nuget push *.nupkg -Source "GitHub" -SkipDuplicate
      shell: bash
