name: .NET Core

on: [push]

jobs:
  testStuffOut:
    runs-on: windows-latest
    steps:
    - name: see if msbuild is installed
      run: |
        ls "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\\MSBuild\Current\Bin"
