name: .NET Core

on: [push]

jobs:
  testStuffOut:
    runs-on: windows-latest
    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1
    # use msbuild to build VS solution
    - name: test
      run: |
        ls
    - name: download nuget
      uses: warrenbuckley/Setup-Nuget@v1
    - name: restore nuget packages
      run: |
        echo "nuget.exe restore TestGit.sln"
        nuget.exe restore TestGit.sln
    - name: build solution
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\MSBuild.exe"
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" TestGit.sln
      shell: cmd
    - name: run tests
      run: |
        echo "TestGit\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe TestGit.Tests\bin\Debug\TestGit.Tests.dll"
        "TestGit\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" TestGit.Tests\bin\Debug\TestGit.Tests.dll
      shell: cmd

